#!/usr/bin/env bash
set -euo pipefail
readonly NAME="CachyOS Edu-Lab" VER="1.1.0" LOG="/var/log/cachyos-edu-lab.log" TMP="/tmp/edulab.tmp"
readonly JS_PORT=3000 DVWA_PORT=8080 JS_NAME="edu-lab-juice-shop" DVWA_NAME="edu-lab-dvwa"
if [[ -t 1 ]]; then R="\033[1;31m" G="\033[1;32m" Y="\033[1;33m" B="\033[1;34m" X="\033[0m"; else R=""; G=""; Y=""; B=""; X=""; fi
log(){ local l="$1"; shift; local t; t="$(date '+%F %T')"; local c="$B"; case "$l" in OK) c="$G";; WARN) c="$Y";; ERROR) c="$R";; esac; printf "%b[%s] [%-5s]%b %s\n" "$c" "$t" "$l" "$X" "$*"; echo "[$t] [$l] $*" >>"$LOG" 2>/dev/null||:; }
i(){ log INFO "$@";}; k(){ log OK "$@";}; w(){ log WARN "$@";}; e(){ log ERROR "$@";}
D=0; on_exit(){ local c=$?; if ((D==0)); then D=1; ((c!=0))&&e "Exit code $c"; tput cnorm 2>/dev/null||:; [[ -f ${TMP:-} ]]&&rm -f "$TMP"||:; fi; exit "$c"; }
trap on_exit EXIT; trap 'e SIGINT; exit 130' INT; trap 'e SIGTERM; exit 143' TERM
root(){ [[ $EUID -eq 0 ]]&&return 0; command -v sudo >/dev/null&&{ w "Re-launching with sudo"; exec sudo -E bash "$0" "$@"; }||{ e "Root required"; exit 1; }; }
distro(){ [[ -f /etc/os-release ]]||{ e "No /etc/os-release"; exit 1; }; . /etc/os-release; [[ "${ID_LIKE:-}${ID:-}" == *arch* || "${ID_LIKE:-}${ID:-}" == *cachyos* ]]||{ w "Non-Arch distro ($ID)"; whiptail --title "Unsupported" --yesno "Continue anyway?" 8 50||exit 1; }; k "Distro OK (${PRETTY_NAME:-?})"; }
pac_install(){ local p="$1"; pacman -Qi "$p">/dev/null&&{ i "$p present"; return 0;}; i "Install $p"; pacman -S --noconfirm --needed "$p">/dev/null 2>&1||{ w "Retry $p"; pacman -Sy --noconfirm>/dev/null 2>&1||return 1; pacman -S --noconfirm --needed "$p">/dev/null 2>&1||{ e "Fail $p"; return 1;};}; k "Installed $p"; }
aur_pac(){ local p="$1"; pacman -Qi "$p">/dev/null&&{ i "$p present"; return 0;}; if command -v paru>/dev/null; then i "paru $p"; paru -S --noconfirm --needed "$p">/dev/null 2>&1&&{ k "paru $p"; return 0;}; w "paru fail $p"; fi; pac_install "$p"; }
whiptail_boot(){ command -v whiptail>/dev/null&&return 0; i "Install whiptail"; pacman -S --noconfirm --needed libnewt>/dev/null 2>&1||{ pacman -Sy --noconfirm>/dev/null 2>&1||{ e "DB refresh fail"; exit 1;}; pacman -S --noconfirm --needed libnewt>/dev/null 2>&1||{ e "libnewt fail"; exit 1;};}; k "whiptail ready"; }
docker_boot(){ command -v docker>/dev/null||{ i "Install docker"; pac_install docker; pac_install docker-compose||:; }; systemctl is-active --quiet docker||{ i "Start docker"; systemctl enable --now docker>/dev/null 2>&1||{ e "docker start fail"; return 1;};}; [[ -n ${SUDO_USER:-} ]]&&{ id -nG "$SUDO_USER" 2>/dev/null|grep -qw docker||{ usermod -aG docker "$SUDO_USER"||w "grp add fail"; w "Re-login for docker grp"; };}; k "Docker OK"; }
pull(){ docker image inspect "$1">/dev/null 2>&1&&{ i "Image $1"; return 0;}; i "Pull $1"; docker pull "$1">/dev/null 2>&1||{ e "Pull fail $1"; return 1;}; k "Pulled $1"; }
deploy(){ local n="$1" im="$2" hp="$3" cp="$4"; shift 4; docker ps -a --format '{{.Names}}'|grep -qx "$n"&&{ w "Removing $n"; docker rm -f "$n">/dev/null 2>&1||:;}; i "Run $n on $hp:$cp"; docker run -d --name "$n" -p "$hp:$cp" "$@" "$im">/dev/null||{ e "Run fail $n"; return 1;}; k "$n up"; }
cyber(){ whiptail --title "Cybersecurity Lab" --msgbox "Deploy:\n  Juice Shop -> http://localhost:$JS_PORT\n  DVWA       -> http://localhost:$DVWA_PORT" 12 66; docker_boot||return 1; pull bkimminich/juice-shop||return 1; deploy "$JS_NAME" bkimminich/juice-shop "$JS_PORT" 3000||return 1; pull vulnerables/web-dvwa||return 1; deploy "$DVWA_NAME" vulnerables/web-dvwa "$DVWA_PORT" 80||return 1; sleep 2; k "Running: $(docker ps --format '{{.Names}}'|tr '\n' ' ')"; whiptail --title "Lab Ready" --msgbox "Juice Shop: http://localhost:$JS_PORT\nDVWA:       http://localhost:$DVWA_PORT (admin/password)\n\nINTENTIONALLY vulnerable - keep on localhost." 14 66; }
dev(){ whiptail --title "Software & AI Dev" --msgbox "Install: Python, pip, Git, Node, npm, Docker, VS Code" 10 66; local p; for p in git base-devel cmake python python-pip python-virtualenv nodejs npm; do pac_install "$p"||w "Skip $p"; done; aur_pac yarn||w "No yarn"; docker_boot||w "Docker issue"; aur_pac code||{ w "No code; trying vscodium"; aur_pac vscodium||w "No vscodium"; }; whiptail --title "Dev Ready" --msgbox "python3 --version\nnode --version\ngit --version\ncode ." 12 66; }
cleaner(){ whiptail --title "Reset Lab" --yesno "Remove ALL containers, volumes, images, and pacman cache?" 10 66||{ i "Cancelled"; return 0;}; if command -v docker>/dev/null; then i "Purge containers"; local c; c="$(docker ps -aq||:)"; [[ -n $c ]]&&docker rm -f $c>/dev/null 2>&1||:; local v; v="$(docker volume ls -q||:)"; [[ -n $v ]]&&docker volume rm -f $v>/dev/null 2>&1||:; docker network prune -f>/dev/null 2>&1||:; docker image prune -af>/dev/null 2>&1||:; docker builder prune -af>/dev/null 2>&1||:; k "Docker purged"; else w "No docker"; fi; i "Clean pacman cache"; if command -v paccache>/dev/null; then paccache -rk0>/dev/null 2>&1||w "paccache fail"; else pacman -Scc --noconfirm>/dev/null 2>&1||w "cache fail"; fi; k "Cache cleaned"; whiptail --title "Reset Done" --msgbox "Lab restored." 8 50; }
status(){ local ds="not installed"; command -v docker>/dev/null&&{ systemctl is-active --quiet docker&&ds="running"||ds="stopped"; }; local ctr="<none>"; [[ $ds == running ]]&&{ ctr="$(docker ps --format '  * {{.Names}} -> {{.Ports}}' 2>/dev/null||:)"; [[ -z $ctr ]]&&ctr="<none>"; }; whiptail --title "Status" --msgbox "Host: $(hostname)\nKernel: $(uname -r)\nCPU: $(grep -m1 'model name' /proc/cpuinfo|cut -d: -f2|sed 's/^ *//')\nMem: $(free -h|awk '/^Mem:/{print $2}')\nDocker: $ds\n\nContainers:\n$ctr" 18 74; }
menu(){ : >"$TMP"; while :; do local c=""; if ! whiptail --title "$NAME v$VER" --menu "Select:" 18 74 10 1 "Cybersecurity Lab (Juice Shop + DVWA)" 2 "Software & AI Dev Class" 3 "Lab Reset & Cleanup" 4 "System / Docker status" 0 "Exit" 3>"$TMP" 1>&2 2>&3; then i "Menu cancelled"; return 0; fi; c="$(cat "$TMP" 2>/dev/null||:)"; case "$c" in 1) cyber;; 2) dev;; 3) cleaner;; 4) status;; 0) i "Bye"; return 0;; *) w "Bad choice '$c'";; esac; done; }
main(){ root "$@"; whiptail_boot; distro; i "Log: $LOG"; menu; }
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
